# Generated by Django 2.2.17 on 2020-12-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201209_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='jhgjhghj',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
